### TODO#12
### Completa los ... de las siguientes peticiones por orden,
### para probar el API con el plugin REST CLIENT de VsCode

### Create user

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Paula",
  "email": "paula@http.com",
  "role": "USER",
  "password": "Ab123456"
}


### Login

POST http://localhost:8080/api/users/me/session
Content-Type: application/json

{
  "email": "paula@http.com",
  "password": "Ab123456"
}


### Profile

GET http://localhost:8080/api/users/me
Content-Type: application/json
Cookie: session=a2db14b5-bcbd-4a68-a632-3eec39974ba5



